### ISSUE TITLE
Formulaire de contact

### ISSUE THREAD

**Issue by kewou** [kewou/AngularProject#11]
Contrôle des informations saisies avant soumission

**Comment by cnantch** [comment]
le formulaire de contact a été fait. cependant il semblerait que le mail ne part pas. on va vérifier ce qu'il en est?

**Comment by kewou** [comment]
Après click envoi du message, si c'est ok coté back message sous forme de boite model ( Message Envoyé :+1: ) ensuite on recharge la page contact ( en tout cas on vide le formulaire )

**Comment by kewou** [comment]
Done
