### ISSUE TITLE
Formulaire inscription

### ISSUE THREAD

**Issue by kewou** [kewou/AngularProject#9]
Ajouter un champ de conformation du mot de passe et faire un contrôle avant soumission

**Comment by kewou** [comment]
Rediriger vers la bonne route en fonction du rôle de l'utilisateur

**Comment by kewou** [comment]
Contenu du mail : 

Sujet = "Beezyweb : Validation de votre compte";      
Contenu= "Bonjour Cyrille Nantchouang ,\n\n" +
              "Merci de vous être inscrit sur notre site. " +
              "Veuillez cliquer sur le lien suivant pour valider votre inscription : \n" +
              verificationUrl + "\n\n" +
              "Si vous n'avez pas créé de compte, veuillez ignorer cet email.\n\n" +
              "Cordialement,\n" +
              "L'équipe Beezyweb (lien cliquable qui redirrige vers https://beezyweb.net";

**Comment by cnantch** [comment]
rajouter la possibilité de voir le mot de passe

**Comment by kewou** [comment]
Lorsqu'on clique sur inscription, rajouter un spinner (chargement) si tout est ok,modifier le contenu de la page en disant qu'un mail à été envoyé à l'adresse mail de l'user, veuillez vous connectez à votre boite mail afin de valider votre inscription.

**Comment by kewou** [comment]
Contenu du mail, il faut envoyer du html afin d'éviter ça : 
L'équipe <a href='https://beezyweb.net/'>BeezyWeb </a>

**Comment by cnantch** [comment]
> Lorsqu'on clique sur inscription, rajouter un spinner (chargement) si tout est ok,modifier le contenu de la page en disant qu'un mail à été envoyé à l'adresse mail de l'user, veuillez vous connectez à votre boite mail afin de valider votre inscription.

Du coup, quand tout s'est bien passé , le message Un mail à été envoyé à l'adresse mail de l'user, veuillez vous connectez à votre boite mail afin de valider votre inscription. doit être affiché 
- en dessous du formulaire 
- en lieu et place du formulaire

ça doit se présenter sous cette forme
![image](https://github.com/kewou/AngularProject/assets/5655682/c4272c6e-583f-4fd2-8487-9d625ee9f5a7)

Ou plutôt sous cette forme
![image](https://github.com/kewou/AngularProject/assets/5655682/b6e86288-ac97-4bff-8a2e-3f6031318fee)

**Comment by kewou** [comment]
Je dirai plustot la seconde image mais envore mieux, l'idee est d'afficher le message via une boite modale un peu comme quand tu clique sur deconnexion.

**Comment by kewou** [comment]
Done
